services:
  database:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ttd-data:/data/db
    networks:
      - ttd-net

  article-ms:
    build:
      context: ./microservices/article-ms
    depends_on:
      - database
    ports:
      - "3002:3002"
    environment:
      - DB_URL_DEV=mongodb://database:27017/ttd
    networks:
      - ttd-net
  auth-service:
    image: birisi/ttd-auth-service:v1.0.0
    depends_on:
      - database
    ports:
      - "3001:3001"
    environment:
      - DB_URL_DEV=mongodb://database:27017/ttd
      - JWT_SECRET=Compaqaley
    networks:
      - ttd-net

  frontend:
    image: birisi/ttd-client:v1.0.0
    depends_on:
      - article-ms
    ports:
      - "4000:5172"
    environment:
      - VITE_SIGNIN_ENDPOINT=http://localhost:3001/signin
      - VITE_SIGNUP_ENDPOINT=http://localhost:3001/signup
      - VITE_API_BASE_URL=http://localhost:3002
    networks:
      - ttd-net

volumes:
  ttd-data:

networks:
  ttd-net:
    driver: bridge
