name: Initialize Branch

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: "Name for the branch"
        required: false
        default: "new-feature"

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Create and push new branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name="${{ github.event.inputs.branchName }}"
          git branch "$branch_name" 
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository}} "$branch_name"
